"""
        Purpose : cleans data/raw/sales_data_raw.csv by 
                  removing invalid rows with negative values, 
                  trimming whitespace and column names, and 
                  handling missing values.
"""
import pandas as pd

# method to read in sales_data_raw.csv from data/raw/.
# Why : doing it to "clean" the .csv.
def load_data(file_path:str):
        return pd.read_csv(file_path) # generated by Github Copilot.

# method to make the column names lowercased and underscores in the .csv.
# Why : To make the column names have the same style and look professional.
def clean_column_names(df):
        df.columns = df.columns.str.strip().str.lower().str.replace(' ', '_')
        return df

# method to deal with empty cells in the csv
# Why : we either remove the cell or fill it in with an empty value. For proper data collection.
def handle_missing_values(df):
        df = df.dropna()
        return df

# method to remove invalid rows in the csv.
# Why : invalid rows spoil the data. rows that have negative quantity or price.
def remove_invalid_rows(df):
        df.loc[:, 'qty'] = pd.to_numeric(df['qty'], errors='coerce')  # generated by Github Copilot.
        df.loc[:, 'price'] = pd.to_numeric(df['price'], errors='coerce') 
        df = df[(df['qty'] >= 0) & (df['price'] >= 0)]
        df.loc[:, 'qty'] = df['qty'].astype(int) # done myself to make the quantity an integer.
        df.loc[:, 'price'] = df['price'].astype(float) # done myself to make the price a float.
        return df

# method to strip leading/trailing whitespace from string columns
# Why : to ensure consistent data formatting and remove accidental spaces
# generated by Github Copilot.
def trim_whitespace(df):
        string_columns = df.select_dtypes(include=['object']).columns
        for col in string_columns:
                df.loc[:, col] = df[col].str.rstrip().lstrip() # added lstrip() to remove leading whitespace as well.
        return df

if __name__ == "__main__":
        raw_path = "data/raw/sales_data_raw.csv"
        cleaned_path = "data/processed/sales_data_clean.csv"

        df_raw = load_data(raw_path)
        df_clean = clean_column_names(df_raw)
        df_clean = handle_missing_values(df_clean)
        df_clean = remove_invalid_rows(df_clean)
        df_clean.to_csv(cleaned_path, index=False)
        print("Cleaning complete. First few rows:")
        print(df_clean.head())
